//! Compound leaves — the recursive case. A compound leaf is leaflets borne on
//! a rachis (pinnate: ash, walnut) or radiating from one point (palmate: horse
//! chestnut; trifoliate: clover). Each leaflet is a full leaf generated by the
//! ordinary pipeline (blade + venation), then rotated/translated into place and
//! its veins merged into the whole.

use crate::blade::{Blade, Margin};
use crate::major::{self, MajorParams, SecondaryArch};
use crate::rng::Rng;
use crate::vec2::Vec2;
use crate::venation::{self, AnastomoseParams, MinorParams, VeinGraph};
use crate::Scalar;

/// A leaf assembled from one or more lamina polygons + a single vein graph.
pub struct Leaf {
    pub laminae: Vec<Vec<Vec2>>,
    pub veins: VeinGraph,
    pub petiole_len: Scalar,
}

/// Map a leaflet-local point (midrib on +y, base at origin) to world space:
/// local +y → unit direction `d`, base → `base`.
fn place(base: Vec2, d: Vec2, p: Vec2) -> Vec2 {
    Vec2::new(base.x + p.x * d.y + p.y * d.x, base.y - p.x * d.x + p.y * d.y)
}

fn rot(v: Vec2, ang: Scalar) -> Vec2 {
    Vec2::new(v.x * ang.cos() - v.y * ang.sin(), v.x * ang.sin() + v.y * ang.cos())
}

/// Assemble a midrib-based leaf: major venation + reticulate minor venation,
/// with venation params auto-scaled to the blade size. `density` scales the
/// source count (1.0 = full); `outline_n` is the outline sample count.
pub fn assemble(
    blade: &Blade,
    arch: SecondaryArch,
    n_sec: usize,
    seed: u64,
    density: Scalar,
    outline_n: usize,
) -> (Vec<Vec2>, VeinGraph) {
    let mp = MajorParams {
        arch,
        n_secondaries: n_sec.max(1),
        first_t: 0.14,
        last_t: 0.82,
        ..MajorParams::default()
    };
    let mut veins = major::build_major(blade, &mp);

    let f = blade.length / 10.0; // venation defaults are tuned for length ~10
    let minor = MinorParams {
        influence_radius: 0.6 * f,
        kill_radius: 0.10 * f,
        step: 0.09 * f,
        seed_clearance: 0.16 * f,
        max_iters: 400,
        max_order: 4,
    };
    let mut rng = Rng::new(seed);
    let area_scale = (blade.length * blade.half_width) / 32.0;
    let n_sources = (5000.0 * area_scale * density).clamp(0.0, 6000.0) as usize;
    venation::grow_minor(&mut veins, blade.sample_sources(n_sources, &mut rng), &minor);
    venation::anastomose(&mut veins, &AnastomoseParams { radius: 0.17 * f, ancestor_depth: 4 });

    (blade.outline(outline_n), veins)
}

fn build_leaflet(blade: &Blade, arch: SecondaryArch, seed: u64, density: Scalar) -> (Vec<Vec2>, VeinGraph) {
    assemble(blade, arch, 6, seed, density, 300)
}

/// Pinnately compound (ash/walnut): leaflet pairs along a rachis + a terminal
/// leaflet (odd-pinnate).
pub fn pinnately_compound(seed: u64, n_pairs: usize, density: Scalar) -> Leaf {
    let n_pairs = n_pairs.max(2);
    let rachis_len = 12.0;
    let petiolule = 0.25;
    let div = 60.0_f64.to_radians();

    let mut veins = VeinGraph::new();
    let rsteps = 48;
    let mut prev = veins.add_node(Vec2::new(0.0, 0.0), 0);
    let mut rachis: Vec<(Scalar, usize)> = vec![(0.0, prev)];
    for k in 1..=rsteps {
        let t = k as Scalar / rsteps as Scalar;
        prev = veins.add_child(prev, Vec2::new(0.0, t * rachis_len), 0);
        rachis.push((t, prev));
    }
    let nearest_rachis = |t: Scalar| -> usize {
        rachis
            .iter()
            .min_by(|a, b| (a.0 - t).abs().partial_cmp(&(b.0 - t).abs()).unwrap())
            .unwrap()
            .1
    };

    let leaflet = Blade::shape(3.4, 1.05, 1.5, 2.1).with_margin(Margin { kind: crate::blade::MarginType::Serrate, n_teeth: 15, amp: 0.07 });
    let terminal = Blade::shape(3.8, 1.15, 1.5, 2.1).with_margin(Margin { kind: crate::blade::MarginType::Serrate, n_teeth: 16, amp: 0.07 });

    let mut laminae = Vec::new();
    for i in 0..n_pairs {
        let t = 0.18 + (0.94 - 0.18) * i as Scalar / (n_pairs as Scalar - 1.0);
        let rn = nearest_rachis(t);
        let attach = veins.nodes[rn];
        for (k, &s) in [1.0 as Scalar, -1.0].iter().enumerate() {
            let d = Vec2::new(s * div.sin(), div.cos()).normalized();
            let base = attach.add(d.scale(petiolule));
            let (ol, vl) = build_leaflet(&leaflet, SecondaryArch::Brochidodromous, seed + (i * 2 + k) as u64 * 17 + 1, density);
            let off = veins.append_transformed(&vl, |p| place(base, d, p));
            veins.add_edge(rn, off, 1); // petiolule
            laminae.push(ol.iter().map(|p| place(base, d, *p)).collect());
        }
    }
    // terminal leaflet, pointing along the rachis
    let top = *rachis.last().unwrap();
    let d = Vec2::new(0.0, 1.0);
    let base = veins.nodes[top.1].add(d.scale(petiolule));
    let (ol, vl) = build_leaflet(&terminal, SecondaryArch::Brochidodromous, seed + 999, density);
    let off = veins.append_transformed(&vl, |p| place(base, d, p));
    veins.add_edge(top.1, off, 1);
    laminae.push(ol.iter().map(|p| place(base, d, *p)).collect());

    Leaf { laminae, veins, petiole_len: rachis_len * 0.14 }
}

/// One pinna (a sub-rachis bearing a row of tiny leaflets) attached at
/// `attach_node`, growing in direction `d`.
fn place_pinna(
    veins: &mut VeinGraph,
    laminae: &mut Vec<Vec<Vec2>>,
    leaflet: &Blade,
    attach_node: usize,
    d: Vec2,
    pinna_len: Scalar,
    n_leaflets: usize,
    seed: &mut u64,
) {
    let attach = veins.nodes[attach_node];
    let mut subprev = attach_node;
    let mut subnodes = Vec::with_capacity(n_leaflets);
    for j in 1..=n_leaflets {
        let f = j as Scalar / n_leaflets as Scalar;
        subprev = veins.add_child(subprev, attach.add(d.scale(pinna_len * f)), 1);
        subnodes.push(subprev);
    }
    let leaf_dir = 72.0_f64.to_radians();
    for &sn in &subnodes {
        for &ls in &[1.0 as Scalar, -1.0] {
            let ldir = rot(d, ls * leaf_dir);
            let lbase = veins.nodes[sn].add(ldir.scale(0.03));
            // tiny pinnules: midrib + a few secondaries only (density 0)
            let (ol, vl) = assemble(leaflet, SecondaryArch::Craspedodromous, 3, *seed, 0.0, 90);
            *seed = seed.wrapping_add(7);
            let off = veins.append_transformed(&vl, |p| place(lbase, ldir, p));
            veins.add_edge(sn, off, 2);
            laminae.push(ol.iter().map(|p| place(lbase, ldir, *p)).collect());
        }
    }
}

/// Bipinnately compound (mimosa, jacaranda): a rachis bearing pinnae, each of
/// which bears a row of tiny pinnules. Twice-recursive.
pub fn bipinnately_compound(seed: u64, n_pinnae: usize, n_leaflets: usize) -> Leaf {
    let n_pinnae = n_pinnae.max(2);
    let n_leaflets = n_leaflets.max(3);
    let rachis_len = 12.0;
    let pinna_len = 4.2;
    let div = 60.0_f64.to_radians();

    let mut veins = VeinGraph::new();
    let steps = 48;
    let mut prev = veins.add_node(Vec2::new(0.0, 0.0), 0);
    let mut rachis = vec![(0.0, prev)];
    for k in 1..=steps {
        let t = k as Scalar / steps as Scalar;
        prev = veins.add_child(prev, Vec2::new(0.0, t * rachis_len), 0);
        rachis.push((t, prev));
    }
    let nearest = |t: Scalar| {
        rachis
            .iter()
            .min_by(|a, b| (a.0 - t).abs().partial_cmp(&(b.0 - t).abs()).unwrap())
            .unwrap()
            .1
    };

    let leaflet = Blade::shape(1.15, 0.34, 1.4, 1.8);
    let mut laminae = Vec::new();
    let mut sid = seed;

    for i in 0..n_pinnae {
        let t = 0.16 + (0.90 - 0.16) * i as Scalar / (n_pinnae as Scalar - 1.0);
        let mn = nearest(t);
        for &s in &[1.0 as Scalar, -1.0] {
            let d = Vec2::new(s * div.sin(), div.cos()).normalized();
            place_pinna(&mut veins, &mut laminae, &leaflet, mn, d, pinna_len, n_leaflets, &mut sid);
        }
    }
    let top = rachis.last().unwrap().1;
    place_pinna(&mut veins, &mut laminae, &leaflet, top, Vec2::new(0.0, 1.0), pinna_len, n_leaflets, &mut sid);

    Leaf { laminae, veins, petiole_len: rachis_len * 0.14 }
}

/// Palmately compound (horse chestnut): `n` leaflets radiating from the petiole
/// tip. `n == 3` gives a trifoliate (clover).
pub fn palmately_compound(seed: u64, n: usize, spread_deg: Scalar, density: Scalar) -> Leaf {
    let mut veins = VeinGraph::new();
    let center = veins.add_node(Vec2::new(0.0, 0.0), 0);
    let petiolule = 0.2;
    let spread = spread_deg.to_radians();

    // Obovate leaflets (widest near the tip), as in horse chestnut.
    let leaflet = Blade::shape(5.2, 1.7, 2.1, 1.4);

    let mut laminae = Vec::new();
    for i in 0..n {
        let frac = if n == 1 { 0.5 } else { i as Scalar / (n as Scalar - 1.0) };
        let ang = -spread + 2.0 * spread * frac;
        let d = Vec2::new(ang.sin(), ang.cos()).normalized();
        let base = veins.nodes[center].add(d.scale(petiolule));
        let (ol, vl) = build_leaflet(&leaflet, SecondaryArch::Brochidodromous, seed + i as u64 * 31 + 3, density);
        let off = veins.append_transformed(&vl, |p| place(base, d, p));
        veins.add_edge(center, off, 0); // thick petiolule
        laminae.push(ol.iter().map(|p| place(base, d, *p)).collect());
    }

    Leaf { laminae, veins, petiole_len: 1.4 }
}
